zendesk:
  uri: "![DA5SQwz5DocP2HfvzQxhi0wDYcTFRWRJTjtY4/npmqI=]"
  user: "![SaQsHkC16unfS9Y2j8bwGTbAyopXPVa74lHjpSKGrg8=]"
  token: "![vpurd0a/veK4Jsq9pbEXLvUWkCRVXMpyVEmp5cn5FIH0g/0rawUe7fOGa/cMX7p4]"
